# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cblocks_pb2 as cblocks__pb2


class CBlocksStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ComputeRank = channel.unary_unary(
        '/cbservice.CBlocks/ComputeRank',
        request_serializer=cblocks__pb2.ConformalBlocksRequest.SerializeToString,
        response_deserializer=cblocks__pb2.IntReply.FromString,
        )
    self.SymComputeRank = channel.unary_unary(
        '/cbservice.CBlocks/SymComputeRank',
        request_serializer=cblocks__pb2.SymConformalBlocksRequest.SerializeToString,
        response_deserializer=cblocks__pb2.IntReply.FromString,
        )
    self.SymComputeDivisor = channel.unary_unary(
        '/cbservice.CBlocks/SymComputeDivisor',
        request_serializer=cblocks__pb2.SymConformalBlocksRequest.SerializeToString,
        response_deserializer=cblocks__pb2.VectorReply.FromString,
        )


class CBlocksServicer(object):
  """The greeting service definition.
  """

  def ComputeRank(self, request, context):
    """Computes the rank of a symmetric conformal blocks bundle
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SymComputeRank(self, request, context):
    """Computes the rank of a symmetric conformal blocks bundle
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SymComputeDivisor(self, request, context):
    """Computes the divisor of the symmetric conformal blocks bundle
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CBlocksServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ComputeRank': grpc.unary_unary_rpc_method_handler(
          servicer.ComputeRank,
          request_deserializer=cblocks__pb2.ConformalBlocksRequest.FromString,
          response_serializer=cblocks__pb2.IntReply.SerializeToString,
      ),
      'SymComputeRank': grpc.unary_unary_rpc_method_handler(
          servicer.SymComputeRank,
          request_deserializer=cblocks__pb2.SymConformalBlocksRequest.FromString,
          response_serializer=cblocks__pb2.IntReply.SerializeToString,
      ),
      'SymComputeDivisor': grpc.unary_unary_rpc_method_handler(
          servicer.SymComputeDivisor,
          request_deserializer=cblocks__pb2.SymConformalBlocksRequest.FromString,
          response_serializer=cblocks__pb2.VectorReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cbservice.CBlocks', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
