# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cblocks_pb2 as cblocks__pb2


class CBlocksStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Sum = channel.unary_unary(
        '/cbservice.CBlocks/Sum',
        request_serializer=cblocks__pb2.Weight.SerializeToString,
        response_deserializer=cblocks__pb2.IntReply.FromString,
        )
    self.ComputeRank = channel.unary_unary(
        '/cbservice.CBlocks/ComputeRank',
        request_serializer=cblocks__pb2.SymConformalBlocksRequest.SerializeToString,
        response_deserializer=cblocks__pb2.IntReply.FromString,
        )


class CBlocksServicer(object):
  """The greeting service definition.
  """

  def Sum(self, request, context):
    """Computes the sum of the coordinates of a weight
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ComputeRank(self, request, context):
    """Computes the rank of the conformal blocks bundle
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CBlocksServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Sum': grpc.unary_unary_rpc_method_handler(
          servicer.Sum,
          request_deserializer=cblocks__pb2.Weight.FromString,
          response_serializer=cblocks__pb2.IntReply.SerializeToString,
      ),
      'ComputeRank': grpc.unary_unary_rpc_method_handler(
          servicer.ComputeRank,
          request_deserializer=cblocks__pb2.SymConformalBlocksRequest.FromString,
          response_serializer=cblocks__pb2.IntReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cbservice.CBlocks', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
