// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cblocks.proto

package cbservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LieAlgebra_LieType int32

const (
	LieAlgebra_A LieAlgebra_LieType = 0
	LieAlgebra_B LieAlgebra_LieType = 1
	LieAlgebra_C LieAlgebra_LieType = 2
	LieAlgebra_D LieAlgebra_LieType = 3
)

var LieAlgebra_LieType_name = map[int32]string{
	0: "A",
	1: "B",
	2: "C",
	3: "D",
}
var LieAlgebra_LieType_value = map[string]int32{
	"A": 0,
	"B": 1,
	"C": 2,
	"D": 3,
}

func (x LieAlgebra_LieType) String() string {
	return proto.EnumName(LieAlgebra_LieType_name, int32(x))
}
func (LieAlgebra_LieType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cblocks_fbc214479e1d1e59, []int{1, 0}
}

type SymConformalBlocksRequest struct {
	Algebra              *LieAlgebra `protobuf:"bytes,1,opt,name=algebra,proto3" json:"algebra,omitempty"`
	Weight               *Weight     `protobuf:"bytes,2,opt,name=weight,proto3" json:"weight,omitempty"`
	NumPoints            int64       `protobuf:"varint,3,opt,name=num_points,json=numPoints,proto3" json:"num_points,omitempty"`
	Level                int64       `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SymConformalBlocksRequest) Reset()         { *m = SymConformalBlocksRequest{} }
func (m *SymConformalBlocksRequest) String() string { return proto.CompactTextString(m) }
func (*SymConformalBlocksRequest) ProtoMessage()    {}
func (*SymConformalBlocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cblocks_fbc214479e1d1e59, []int{0}
}
func (m *SymConformalBlocksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SymConformalBlocksRequest.Unmarshal(m, b)
}
func (m *SymConformalBlocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SymConformalBlocksRequest.Marshal(b, m, deterministic)
}
func (dst *SymConformalBlocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SymConformalBlocksRequest.Merge(dst, src)
}
func (m *SymConformalBlocksRequest) XXX_Size() int {
	return xxx_messageInfo_SymConformalBlocksRequest.Size(m)
}
func (m *SymConformalBlocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SymConformalBlocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SymConformalBlocksRequest proto.InternalMessageInfo

func (m *SymConformalBlocksRequest) GetAlgebra() *LieAlgebra {
	if m != nil {
		return m.Algebra
	}
	return nil
}

func (m *SymConformalBlocksRequest) GetWeight() *Weight {
	if m != nil {
		return m.Weight
	}
	return nil
}

func (m *SymConformalBlocksRequest) GetNumPoints() int64 {
	if m != nil {
		return m.NumPoints
	}
	return 0
}

func (m *SymConformalBlocksRequest) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

type LieAlgebra struct {
	Type                 LieAlgebra_LieType `protobuf:"varint,1,opt,name=type,proto3,enum=cbservice.LieAlgebra_LieType" json:"type,omitempty"`
	Rank                 int64              `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LieAlgebra) Reset()         { *m = LieAlgebra{} }
func (m *LieAlgebra) String() string { return proto.CompactTextString(m) }
func (*LieAlgebra) ProtoMessage()    {}
func (*LieAlgebra) Descriptor() ([]byte, []int) {
	return fileDescriptor_cblocks_fbc214479e1d1e59, []int{1}
}
func (m *LieAlgebra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LieAlgebra.Unmarshal(m, b)
}
func (m *LieAlgebra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LieAlgebra.Marshal(b, m, deterministic)
}
func (dst *LieAlgebra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LieAlgebra.Merge(dst, src)
}
func (m *LieAlgebra) XXX_Size() int {
	return xxx_messageInfo_LieAlgebra.Size(m)
}
func (m *LieAlgebra) XXX_DiscardUnknown() {
	xxx_messageInfo_LieAlgebra.DiscardUnknown(m)
}

var xxx_messageInfo_LieAlgebra proto.InternalMessageInfo

func (m *LieAlgebra) GetType() LieAlgebra_LieType {
	if m != nil {
		return m.Type
	}
	return LieAlgebra_A
}

func (m *LieAlgebra) GetRank() int64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

// An integral weight
type Weight struct {
	Coords               []int64  `protobuf:"varint,1,rep,packed,name=coords,proto3" json:"coords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weight) Reset()         { *m = Weight{} }
func (m *Weight) String() string { return proto.CompactTextString(m) }
func (*Weight) ProtoMessage()    {}
func (*Weight) Descriptor() ([]byte, []int) {
	return fileDescriptor_cblocks_fbc214479e1d1e59, []int{2}
}
func (m *Weight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weight.Unmarshal(m, b)
}
func (m *Weight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weight.Marshal(b, m, deterministic)
}
func (dst *Weight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weight.Merge(dst, src)
}
func (m *Weight) XXX_Size() int {
	return xxx_messageInfo_Weight.Size(m)
}
func (m *Weight) XXX_DiscardUnknown() {
	xxx_messageInfo_Weight.DiscardUnknown(m)
}

var xxx_messageInfo_Weight proto.InternalMessageInfo

func (m *Weight) GetCoords() []int64 {
	if m != nil {
		return m.Coords
	}
	return nil
}

// A integer reply message
type IntReply struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntReply) Reset()         { *m = IntReply{} }
func (m *IntReply) String() string { return proto.CompactTextString(m) }
func (*IntReply) ProtoMessage()    {}
func (*IntReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cblocks_fbc214479e1d1e59, []int{3}
}
func (m *IntReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntReply.Unmarshal(m, b)
}
func (m *IntReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntReply.Marshal(b, m, deterministic)
}
func (dst *IntReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntReply.Merge(dst, src)
}
func (m *IntReply) XXX_Size() int {
	return xxx_messageInfo_IntReply.Size(m)
}
func (m *IntReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IntReply.DiscardUnknown(m)
}

var xxx_messageInfo_IntReply proto.InternalMessageInfo

func (m *IntReply) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*SymConformalBlocksRequest)(nil), "cbservice.SymConformalBlocksRequest")
	proto.RegisterType((*LieAlgebra)(nil), "cbservice.LieAlgebra")
	proto.RegisterType((*Weight)(nil), "cbservice.Weight")
	proto.RegisterType((*IntReply)(nil), "cbservice.IntReply")
	proto.RegisterEnum("cbservice.LieAlgebra_LieType", LieAlgebra_LieType_name, LieAlgebra_LieType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CBlocksClient is the client API for CBlocks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CBlocksClient interface {
	// Computes the sum of the coordinates of a weight
	Sum(ctx context.Context, in *Weight, opts ...grpc.CallOption) (*IntReply, error)
	// Computes the rank of the conformal blocks bundle
	ComputeRank(ctx context.Context, in *SymConformalBlocksRequest, opts ...grpc.CallOption) (*IntReply, error)
}

type cBlocksClient struct {
	cc *grpc.ClientConn
}

func NewCBlocksClient(cc *grpc.ClientConn) CBlocksClient {
	return &cBlocksClient{cc}
}

func (c *cBlocksClient) Sum(ctx context.Context, in *Weight, opts ...grpc.CallOption) (*IntReply, error) {
	out := new(IntReply)
	err := c.cc.Invoke(ctx, "/cbservice.CBlocks/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cBlocksClient) ComputeRank(ctx context.Context, in *SymConformalBlocksRequest, opts ...grpc.CallOption) (*IntReply, error) {
	out := new(IntReply)
	err := c.cc.Invoke(ctx, "/cbservice.CBlocks/ComputeRank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CBlocksServer is the server API for CBlocks service.
type CBlocksServer interface {
	// Computes the sum of the coordinates of a weight
	Sum(context.Context, *Weight) (*IntReply, error)
	// Computes the rank of the conformal blocks bundle
	ComputeRank(context.Context, *SymConformalBlocksRequest) (*IntReply, error)
}

func RegisterCBlocksServer(s *grpc.Server, srv CBlocksServer) {
	s.RegisterService(&_CBlocks_serviceDesc, srv)
}

func _CBlocks_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Weight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CBlocksServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cbservice.CBlocks/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CBlocksServer).Sum(ctx, req.(*Weight))
	}
	return interceptor(ctx, in, info, handler)
}

func _CBlocks_ComputeRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymConformalBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CBlocksServer).ComputeRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cbservice.CBlocks/ComputeRank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CBlocksServer).ComputeRank(ctx, req.(*SymConformalBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CBlocks_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cbservice.CBlocks",
	HandlerType: (*CBlocksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CBlocks_Sum_Handler,
		},
		{
			MethodName: "ComputeRank",
			Handler:    _CBlocks_ComputeRank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cblocks.proto",
}

func init() { proto.RegisterFile("cblocks.proto", fileDescriptor_cblocks_fbc214479e1d1e59) }

var fileDescriptor_cblocks_fbc214479e1d1e59 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0xdd, 0x4e, 0xc2, 0x30,
	0x14, 0xc7, 0x19, 0x83, 0x21, 0x87, 0x68, 0x66, 0xfd, 0xc8, 0x34, 0x21, 0x21, 0x8d, 0x26, 0x7a,
	0x83, 0x11, 0x9f, 0x00, 0xe6, 0x8d, 0xc6, 0x0b, 0x53, 0x4c, 0xbc, 0x34, 0xdb, 0x3c, 0xe2, 0x42,
	0xb7, 0xce, 0xae, 0xc3, 0xe0, 0x03, 0xf8, 0x34, 0x3e, 0xa4, 0x5d, 0x07, 0xba, 0x44, 0xb9, 0x3a,
	0x5f, 0xbf, 0x9e, 0xf3, 0xef, 0x69, 0x61, 0x3b, 0x0a, 0xb9, 0x88, 0xe6, 0xf9, 0x30, 0x93, 0x42,
	0x09, 0xd2, 0x8d, 0xc2, 0x1c, 0xe5, 0x22, 0x8e, 0x90, 0x7e, 0x59, 0x70, 0x34, 0x5d, 0x26, 0xbe,
	0x48, 0x5f, 0x84, 0x4c, 0x02, 0x3e, 0x31, 0x1c, 0xc3, 0xb7, 0x02, 0x73, 0x45, 0x2e, 0xa0, 0x13,
	0xf0, 0x19, 0x86, 0x32, 0xf0, 0xac, 0x81, 0x75, 0xd6, 0x1b, 0x1d, 0x0c, 0x7f, 0x8e, 0x0e, 0xef,
	0x62, 0x1c, 0x57, 0x45, 0xb6, 0xa6, 0xc8, 0x39, 0x38, 0xef, 0x18, 0xcf, 0x5e, 0x95, 0xd7, 0x34,
	0xfc, 0x6e, 0x8d, 0x7f, 0x34, 0x05, 0xb6, 0x02, 0x48, 0x1f, 0x20, 0x2d, 0x92, 0xa7, 0x4c, 0xc4,
	0xa9, 0xca, 0x3d, 0x5b, 0xe3, 0x36, 0xeb, 0xea, 0xcc, 0xbd, 0x49, 0x90, 0x7d, 0x68, 0x73, 0x5c,
	0x20, 0xf7, 0x5a, 0xa6, 0x52, 0x05, 0xf4, 0x03, 0xe0, 0x77, 0x2c, 0xb9, 0x84, 0x96, 0x5a, 0x66,
	0x68, 0xb4, 0xed, 0x8c, 0xfa, 0xff, 0x6a, 0x2b, 0xdd, 0x07, 0x0d, 0x31, 0x83, 0x12, 0x02, 0x2d,
	0x19, 0xa4, 0x73, 0x23, 0xcf, 0x66, 0xc6, 0xa7, 0xa7, 0xd0, 0x59, 0x41, 0xa4, 0x0d, 0xd6, 0xd8,
	0x6d, 0x94, 0x66, 0xe2, 0x5a, 0xa5, 0xf1, 0xdd, 0x66, 0x69, 0xae, 0x5d, 0x9b, 0x0e, 0xc0, 0xa9,
	0xae, 0x40, 0x0e, 0xc1, 0x89, 0x84, 0x90, 0xcf, 0xb9, 0x9e, 0x6c, 0xeb, 0x36, 0xab, 0x88, 0x52,
	0xd8, 0xba, 0x49, 0x15, 0xc3, 0x8c, 0x2f, 0x4b, 0x46, 0x62, 0x5e, 0x70, 0x65, 0xd4, 0x69, 0xa6,
	0x8a, 0x46, 0x9f, 0x16, 0x74, 0xfc, 0x6a, 0xcb, 0x7a, 0xbd, 0xf6, 0xb4, 0x48, 0xc8, 0xdf, 0x25,
	0x1d, 0xef, 0xd5, 0x52, 0xeb, 0x96, 0xb4, 0x41, 0x6e, 0xa1, 0xe7, 0x8b, 0x24, 0x2b, 0x14, 0x32,
	0x2d, 0x9c, 0x9c, 0xd4, 0xa8, 0x8d, 0x8f, 0xb8, 0xa1, 0x57, 0xe8, 0x98, 0xbf, 0x70, 0xf5, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x47, 0x87, 0x99, 0xaf, 0x1c, 0x02, 0x00, 0x00,
}
